//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freya.Desktop.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Freya.Desktop.Localization.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir cliente.
        /// </summary>
        internal static string add_client {
            get {
                return ResourceManager.GetString("add_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir clínica.
        /// </summary>
        internal static string add_clinic {
            get {
                return ResourceManager.GetString("add_clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir empleado.
        /// </summary>
        internal static string add_employee {
            get {
                return ResourceManager.GetString("add_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añade un nuevo cliente.
        /// </summary>
        internal static string add_new_client_title {
            get {
                return ResourceManager.GetString("add_new_client_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añade un nuevo empleado.
        /// </summary>
        internal static string add_new_employee_title {
            get {
                return ResourceManager.GetString("add_new_employee_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de clínica.
        /// </summary>
        internal static string address_of_clinic {
            get {
                return ResourceManager.GetString("address_of_clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de la aplicación.
        /// </summary>
        internal static string app_info {
            get {
                return ResourceManager.GetString("app_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freya.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freya Manager.
        /// </summary>
        internal static string app_name_manager {
            get {
                return ResourceManager.GetString("app_name_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adquiere una suscripción.
        /// </summary>
        internal static string buy_your_subscription {
            get {
                return ResourceManager.GetString("buy_your_subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        internal static string change_pass {
            get {
                return ResourceManager.GetString("change_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia tu contraseña.
        /// </summary>
        internal static string change_your_pass {
            get {
                return ResourceManager.GetString("change_your_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargos realizados.
        /// </summary>
        internal static string charges_done {
            get {
                return ResourceManager.GetString("charges_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compruebe los campos.
        /// </summary>
        internal static string check_fields {
            get {
                return ResourceManager.GetString("check_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobar actualización.
        /// </summary>
        internal static string check_update {
            get {
                return ResourceManager.GetString("check_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string clients {
            get {
                return ResourceManager.GetString("clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suscripción de la clínica.
        /// </summary>
        internal static string clinic_your_subscription {
            get {
                return ResourceManager.GetString("clinic_your_subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear empleado.
        /// </summary>
        internal static string create_employee {
            get {
                return ResourceManager.GetString("create_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        internal static string currrent_pass {
            get {
                return ResourceManager.GetString("currrent_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado ya registrado y asignado a esta clínica.
        /// </summary>
        internal static string dialog_check_employee_asigned_before_body {
            get {
                return ResourceManager.GetString("dialog_check_employee_asigned_before_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este cliente ya está asignado a esta compañia, si lo que quieres es asignarlo a una clínica en concreto, ve a la pestaña de empleados del detalle de la clínica..
        /// </summary>
        internal static string dialog_check_employee_asigned_before_for_a_company_body {
            get {
                return ResourceManager.GetString("dialog_check_employee_asigned_before_for_a_company_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya asignado.
        /// </summary>
        internal static string dialog_check_employee_asigned_before_for_a_company_title {
            get {
                return ResourceManager.GetString("dialog_check_employee_asigned_before_for_a_company_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya asignado.
        /// </summary>
        internal static string dialog_check_employee_asigned_before_title {
            get {
                return ResourceManager.GetString("dialog_check_employee_asigned_before_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quieres asignarlo a esta clínica?.
        /// </summary>
        internal static string dialog_check_employee_asigned_question_body {
            get {
                return ResourceManager.GetString("dialog_check_employee_asigned_question_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado ya registrado.
        /// </summary>
        internal static string dialog_check_employee_asigned_question_title {
            get {
                return ResourceManager.GetString("dialog_check_employee_asigned_question_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado asignado correctamente a la clínica.
        /// </summary>
        internal static string dialog_check_employee_asigned_success_body {
            get {
                return ResourceManager.GetString("dialog_check_employee_asigned_success_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genial.
        /// </summary>
        internal static string dialog_check_employee_asigned_success_title {
            get {
                return ResourceManager.GetString("dialog_check_employee_asigned_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un empleado no puede estar vinculado a dos compañias diferentes..
        /// </summary>
        internal static string dialog_check_employee_asigned_to_other_company_body {
            get {
                return ResourceManager.GetString("dialog_check_employee_asigned_to_other_company_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este empleado esta asignado a otra compañia distinta.
        /// </summary>
        internal static string dialog_check_employee_asigned_to_other_company_title {
            get {
                return ResourceManager.GetString("dialog_check_employee_asigned_to_other_company_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quieres crear un nuevo empleado?.
        /// </summary>
        internal static string dialog_check_employee_want_register_question_body {
            get {
                return ResourceManager.GetString("dialog_check_employee_want_register_question_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado no existe.
        /// </summary>
        internal static string dialog_check_employee_want_register_question_title {
            get {
                return ResourceManager.GetString("dialog_check_employee_want_register_question_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que quiere eliminar este cliente? Se perderán todos los recursos asosiados como imagenes, videos, etc....
        /// </summary>
        internal static string dialog_client_detail_remove_client_body {
            get {
                return ResourceManager.GetString("dialog_client_detail_remove_client_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar cliente.
        /// </summary>
        internal static string dialog_client_detail_remove_client_title {
            get {
                return ResourceManager.GetString("dialog_client_detail_remove_client_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece que este cliente se creo con una subscripción diferente ¿Quieres actualizar el espacio disponible de este cliente a la nueva subscripción?.
        /// </summary>
        internal static string dialog_client_detail_update_plan_body {
            get {
                return ResourceManager.GetString("dialog_client_detail_update_plan_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar suscripción.
        /// </summary>
        internal static string dialog_client_detail_update_plan_title {
            get {
                return ResourceManager.GetString("dialog_client_detail_update_plan_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cambiado correctamente la contraseña.
        /// </summary>
        internal static string dialog_client_profile_change_pass_success_body {
            get {
                return ResourceManager.GetString("dialog_client_profile_change_pass_success_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña cambiada.
        /// </summary>
        internal static string dialog_client_profile_change_pass_success_title {
            get {
                return ResourceManager.GetString("dialog_client_profile_change_pass_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primero debes crear una cínica antes de poder añadir algún cliente.
        /// </summary>
        internal static string dialog_client_you_need_create_a_clinic_before_a_client_body {
            get {
                return ResourceManager.GetString("dialog_client_you_need_create_a_clinic_before_a_client_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes realizar esta acción.
        /// </summary>
        internal static string dialog_client_you_need_create_a_clinic_before_a_client_Title {
            get {
                return ResourceManager.GetString("dialog_client_you_need_create_a_clinic_before_a_client_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que quiere cancelar esta subscripción? No se devolverá el dinero.
        /// </summary>
        internal static string dialog_clinic_detail_cancel_subscription_clinic_body {
            get {
                return ResourceManager.GetString("dialog_clinic_detail_cancel_subscription_clinic_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya no se realizarán más cobros para la subscripción cancelada.
        /// </summary>
        internal static string dialog_clinic_detail_cancel_subscription_clinic_success_body {
            get {
                return ResourceManager.GetString("dialog_clinic_detail_cancel_subscription_clinic_success_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscripción cancelada.
        /// </summary>
        internal static string dialog_clinic_detail_cancel_subscription_clinic_success_title {
            get {
                return ResourceManager.GetString("dialog_clinic_detail_cancel_subscription_clinic_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar subscripción.
        /// </summary>
        internal static string dialog_clinic_detail_cancel_subscription_clinic_title {
            get {
                return ResourceManager.GetString("dialog_clinic_detail_cancel_subscription_clinic_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que quiere eliminar esta cínica? Se perderán todos los datos asosiados como empleados, clientes, imagenes, videos, etc....
        /// </summary>
        internal static string dialog_clinic_detail_remove_clinic_body {
            get {
                return ResourceManager.GetString("dialog_clinic_detail_remove_clinic_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar clínica.
        /// </summary>
        internal static string dialog_clinic_detail_remove_clinic_title {
            get {
                return ResourceManager.GetString("dialog_clinic_detail_remove_clinic_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para cancelar una subscripción, debes desactivar la subscripción activa.
        /// </summary>
        internal static string dialog_clinic_subscrption_want_cancel_but_has_other_active_body {
            get {
                return ResourceManager.GetString("dialog_clinic_subscrption_want_cancel_but_has_other_active_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes contratar otra subscripción.
        /// </summary>
        internal static string dialog_clinic_subscrption_want_cancel_but_has_other_active_title {
            get {
                return ResourceManager.GetString("dialog_clinic_subscrption_want_cancel_but_has_other_active_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El empleado ha sido creado correctamente, La contraseña de acceso a sido enviada al correo electrónico.
        /// </summary>
        internal static string dialog_create_new_employee_success_body {
            get {
                return ResourceManager.GetString("dialog_create_new_employee_success_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado creado.
        /// </summary>
        internal static string dialog_create_new_employee_success_title {
            get {
                return ResourceManager.GetString("dialog_create_new_employee_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este empleado no esta asociado a ninguna clínica.
        /// </summary>
        internal static string dialog_employee_not_is_manager_and_not_has_any_clinic_body {
            get {
                return ResourceManager.GetString("dialog_employee_not_is_manager_and_not_has_any_clinic_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacta con tu gerente.
        /// </summary>
        internal static string dialog_employee_not_is_manager_and_not_has_any_clinic_title {
            get {
                return ResourceManager.GetString("dialog_employee_not_is_manager_and_not_has_any_clinic_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supera el espacio disponible para este cliente, aumente su plan de subscripción si desea más espacio.
        /// </summary>
        internal static string dialog_error_client_space_available_limited_body {
            get {
                return ResourceManager.GetString("dialog_error_client_space_available_limited_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de espacio disponible.
        /// </summary>
        internal static string dialog_error_client_space_available_limited_title {
            get {
                return ResourceManager.GetString("dialog_error_client_space_available_limited_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta app requiere de internet para funcionar.
        /// </summary>
        internal static string dialog_error_no_internet_body {
            get {
                return ResourceManager.GetString("dialog_error_no_internet_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay internet.
        /// </summary>
        internal static string dialog_error_no_internet_title {
            get {
                return ResourceManager.GetString("dialog_error_no_internet_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes permiso para procesar la solicitud.
        /// </summary>
        internal static string dialog_error_response_forbidden_body {
            get {
                return ResourceManager.GetString("dialog_error_response_forbidden_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string dialog_error_response_forbidden_title {
            get {
                return ResourceManager.GetString("dialog_error_response_forbidden_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe volver a inciar sesin.
        /// </summary>
        internal static string dialog_error_response_unauthorized_body {
            get {
                return ResourceManager.GetString("dialog_error_response_unauthorized_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha caducado la sesin.
        /// </summary>
        internal static string dialog_error_response_unauthorized_title {
            get {
                return ResourceManager.GetString("dialog_error_response_unauthorized_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha detectado un error en la comunicación con el servidor. Por favor, inténtelo de nuevo más tarde.
        /// </summary>
        internal static string dialog_error_server_error_body {
            get {
                return ResourceManager.GetString("dialog_error_server_error_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prueba en otro momento.
        /// </summary>
        internal static string dialog_error_server_not_response_body {
            get {
                return ResourceManager.GetString("dialog_error_server_not_response_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servidor no responde.
        /// </summary>
        internal static string dialog_error_server_not_response_title {
            get {
                return ResourceManager.GetString("dialog_error_server_not_response_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estas seguro de que quieres salir?.
        /// </summary>
        internal static string dialog_menu_close_session_body {
            get {
                return ResourceManager.GetString("dialog_menu_close_session_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        internal static string dialog_menu_close_session_title {
            get {
                return ResourceManager.GetString("dialog_menu_close_session_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un problma con la descarga.
        /// </summary>
        internal static string dialog_multimedia_download_file_fail_body {
            get {
                return ResourceManager.GetString("dialog_multimedia_download_file_fail_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su fichero ha sido descargado.
        /// </summary>
        internal static string dialog_multimedia_download_file_success_body {
            get {
                return ResourceManager.GetString("dialog_multimedia_download_file_success_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarga de archivos.
        /// </summary>
        internal static string dialog_multimedia_download_file_title {
            get {
                return ResourceManager.GetString("dialog_multimedia_download_file_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que quieres eliminar este recurso?.
        /// </summary>
        internal static string dialog_multimedia_remove_body {
            get {
                return ResourceManager.GetString("dialog_multimedia_remove_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar recurso.
        /// </summary>
        internal static string dialog_multimedia_remove_title {
            get {
                return ResourceManager.GetString("dialog_multimedia_remove_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este cliente ya está asignado a esta clínica.
        /// </summary>
        internal static string dialog_new_client_client_assigned_before_body {
            get {
                return ResourceManager.GetString("dialog_new_client_client_assigned_before_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya asignado.
        /// </summary>
        internal static string dialog_new_client_client_assigned_before_title {
            get {
                return ResourceManager.GetString("dialog_new_client_client_assigned_before_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente asignado correctamente a la clínica.
        /// </summary>
        internal static string dialog_new_client_client_assigned_body {
            get {
                return ResourceManager.GetString("dialog_new_client_client_assigned_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genial.
        /// </summary>
        internal static string dialog_new_client_client_assigned_title {
            get {
                return ResourceManager.GetString("dialog_new_client_client_assigned_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quieres crear un nuevo cliente con este correo?.
        /// </summary>
        internal static string dialog_new_client_client_exist_body {
            get {
                return ResourceManager.GetString("dialog_new_client_client_exist_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente no existe.
        /// </summary>
        internal static string dialog_new_client_client_exist_title {
            get {
                return ResourceManager.GetString("dialog_new_client_client_exist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente ya registrado.
        /// </summary>
        internal static string dialog_new_client_client_registered_body {
            get {
                return ResourceManager.GetString("dialog_new_client_client_registered_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quieres asignarlo a esta clínica?.
        /// </summary>
        internal static string dialog_new_client_client_registered_title {
            get {
                return ResourceManager.GetString("dialog_new_client_client_registered_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta clínica no dispone de una suscripción activa.
        /// </summary>
        internal static string dialog_new_client_clinic_not_subscription_valid_body {
            get {
                return ResourceManager.GetString("dialog_new_client_clinic_not_subscription_valid_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clínica sin suscripción.
        /// </summary>
        internal static string dialog_new_client_clinic_not_subscription_valid_title {
            get {
                return ResourceManager.GetString("dialog_new_client_clinic_not_subscription_valid_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente ha sido creado correctamente y se ha enviado su contraseña al correo electrónico.
        /// </summary>
        internal static string dialog_new_client_success_body {
            get {
                return ResourceManager.GetString("dialog_new_client_success_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente creado.
        /// </summary>
        internal static string dialog_new_client_success_title {
            get {
                return ResourceManager.GetString("dialog_new_client_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus datos de perfil han sido actualizados.
        /// </summary>
        internal static string dialog_profile_updated_success_body {
            get {
                return ResourceManager.GetString("dialog_profile_updated_success_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos actualizados.
        /// </summary>
        internal static string dialog_profile_updated_success_title {
            get {
                return ResourceManager.GetString("dialog_profile_updated_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este empleado es dueño o gerente de la compañia, ya tiene acceso a esta clínica..
        /// </summary>
        internal static string dialog_register_employee_can_not_register_employee_manager_to_individual_clinic_body {
            get {
                return ResourceManager.GetString("dialog_register_employee_can_not_register_employee_manager_to_individual_clinic_b" +
                        "ody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado ya registrado.
        /// </summary>
        internal static string dialog_register_employee_can_not_register_employee_manager_to_individual_clinic_title {
            get {
                return ResourceManager.GetString("dialog_register_employee_can_not_register_employee_manager_to_individual_clinic_t" +
                        "itle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estas seguro que quieres restablecer la contraseña?.
        /// </summary>
        internal static string dialog_sign_in_recover_pass_question_body {
            get {
                return ResourceManager.GetString("dialog_sign_in_recover_pass_question_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer contraseña.
        /// </summary>
        internal static string dialog_sign_in_recover_pass_question_title {
            get {
                return ResourceManager.GetString("dialog_sign_in_recover_pass_question_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mire su bandeja de entrada para ver su nueva contraseña.
        /// </summary>
        internal static string dialog_sign_in_recover_pass_success_body {
            get {
                return ResourceManager.GetString("dialog_sign_in_recover_pass_success_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña restablecida.
        /// </summary>
        internal static string dialog_sign_in_recover_pass_success_title {
            get {
                return ResourceManager.GetString("dialog_sign_in_recover_pass_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quieres actualizar la app? Se va a instalar una nueva versión.
        /// </summary>
        internal static string dialog_updater_update_available_body {
            get {
                return ResourceManager.GetString("dialog_updater_update_available_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización disponible.
        /// </summary>
        internal static string dialog_updater_update_available_title {
            get {
                return ResourceManager.GetString("dialog_updater_update_available_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error.
        /// </summary>
        internal static string dialog_updater_update_fail_body {
            get {
                return ResourceManager.GetString("dialog_updater_update_fail_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido actualizar la app.
        /// </summary>
        internal static string dialog_updater_update_fail_title {
            get {
                return ResourceManager.GetString("dialog_updater_update_fail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes la última versión instalada.
        /// </summary>
        internal static string dialog_updater_update_not_available_body {
            get {
                return ResourceManager.GetString("dialog_updater_update_not_available_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es necesario actualizar tu aplicación.
        /// </summary>
        internal static string dialog_updater_update_not_available_title {
            get {
                return ResourceManager.GetString("dialog_updater_update_not_available_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se va ha cerrar y lanzar el instalador.
        /// </summary>
        internal static string dialog_updater_update_success_body {
            get {
                return ResourceManager.GetString("dialog_updater_update_success_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización descargada.
        /// </summary>
        internal static string dialog_updater_update_success_title {
            get {
                return ResourceManager.GetString("dialog_updater_update_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay subidas en progreso.
        /// </summary>
        internal static string download_menu_no_current_downloads {
            get {
                return ResourceManager.GetString("download_menu_no_current_downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargando.
        /// </summary>
        internal static string downloading {
            get {
                return ResourceManager.GetString("downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar los datos de la clínica.
        /// </summary>
        internal static string edit_clinic_data {
            get {
                return ResourceManager.GetString("edit_clinic_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar los datos del empleado.
        /// </summary>
        internal static string edit_data_of_employee {
            get {
                return ResourceManager.GetString("edit_data_of_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edita tus datos.
        /// </summary>
        internal static string edit_your_data {
            get {
                return ResourceManager.GetString("edit_your_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dueño de clínica.
        /// </summary>
        internal static string employee_rol_clinic_manager {
            get {
                return ResourceManager.GetString("employee_rol_clinic_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado clínica.
        /// </summary>
        internal static string employee_rol_clinic_office {
            get {
                return ResourceManager.GetString("employee_rol_clinic_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado de compañía.
        /// </summary>
        internal static string employee_rol_company_manager {
            get {
                return ResourceManager.GetString("employee_rol_company_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dueño de compañía.
        /// </summary>
        internal static string employee_rol_company_owner {
            get {
                return ResourceManager.GetString("employee_rol_company_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados.
        /// </summary>
        internal static string employees {
            get {
                return ResourceManager.GetString("employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagenes.
        /// </summary>
        internal static string images {
            get {
                return ResourceManager.GetString("images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si detecta algún tipo de problema o incidencia, compruebe nuestro listado de preguntas frecuentes. Si no consigue encontrar la solución ahí, siempre puede escribirnos a freya.soft.app@gmail.com. También puede probar a instalar una versión más reciente..
        /// </summary>
        internal static string incidences_body {
            get {
                return ResourceManager.GetString("incidences_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidencias.
        /// </summary>
        internal static string incidences_title {
            get {
                return ResourceManager.GetString("incidences_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string menu_clients {
            get {
                return ResourceManager.GetString("menu_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clínica.
        /// </summary>
        internal static string menu_clinic {
            get {
                return ResourceManager.GetString("menu_clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clínicas.
        /// </summary>
        internal static string menu_clinics {
            get {
                return ResourceManager.GetString("menu_clinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string menu_faqs {
            get {
                return ResourceManager.GetString("menu_faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string menu_settings {
            get {
                return ResourceManager.GetString("menu_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la clínica.
        /// </summary>
        internal static string name_of_clinic {
            get {
                return ResourceManager.GetString("name_of_clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo cliente.
        /// </summary>
        internal static string new_client {
            get {
                return ResourceManager.GetString("new_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva clínica.
        /// </summary>
        internal static string new_clinic {
            get {
                return ResourceManager.GetString("new_clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo empleado.
        /// </summary>
        internal static string new_employee {
            get {
                return ResourceManager.GetString("new_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        internal static string new_pass {
            get {
                return ResourceManager.GetString("new_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF.
        /// </summary>
        internal static string nif {
            get {
                return ResourceManager.GetString("nif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF de la clínica.
        /// </summary>
        internal static string nif_of_clinic {
            get {
                return ResourceManager.GetString("nif_of_clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningún cliente.
        /// </summary>
        internal static string no_clients_found {
            get {
                return ResourceManager.GetString("no_clients_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ninguna clínica.
        /// </summary>
        internal static string no_clinics_found {
            get {
                return ResourceManager.GetString("no_clinics_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningún empleado.
        /// </summary>
        internal static string no_employees_found {
            get {
                return ResourceManager.GetString("no_employees_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay niguna pregunta frecuente.
        /// </summary>
        internal static string no_faqs_found {
            get {
                return ResourceManager.GetString("no_faqs_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ninguna imagen.
        /// </summary>
        internal static string no_images_found {
            get {
                return ResourceManager.GetString("no_images_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningún sonido.
        /// </summary>
        internal static string no_sounds_found {
            get {
                return ResourceManager.GetString("no_sounds_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningún video.
        /// </summary>
        internal static string no_videos_found {
            get {
                return ResourceManager.GetString("no_videos_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir cliente.
        /// </summary>
        internal static string page_title_add_client {
            get {
                return ResourceManager.GetString("page_title_add_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir empleado.
        /// </summary>
        internal static string page_title_add_employee {
            get {
                return ResourceManager.GetString("page_title_add_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha cliente.
        /// </summary>
        internal static string page_title_client_detail {
            get {
                return ResourceManager.GetString("page_title_client_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha clínica.
        /// </summary>
        internal static string page_title_clinic_detail {
            get {
                return ResourceManager.GetString("page_title_clinic_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clínicas.
        /// </summary>
        internal static string page_title_clinics {
            get {
                return ResourceManager.GetString("page_title_clinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar cliente.
        /// </summary>
        internal static string page_title_edit_client {
            get {
                return ResourceManager.GetString("page_title_edit_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar clínica.
        /// </summary>
        internal static string page_title_edit_clinic {
            get {
                return ResourceManager.GetString("page_title_edit_clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar empleado.
        /// </summary>
        internal static string page_title_edit_employee {
            get {
                return ResourceManager.GetString("page_title_edit_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas frecuentes.
        /// </summary>
        internal static string page_title_faq {
            get {
                return ResourceManager.GetString("page_title_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo cliente.
        /// </summary>
        internal static string page_title_new_client {
            get {
                return ResourceManager.GetString("page_title_new_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nueva clínica.
        /// </summary>
        internal static string page_title_new_clinic {
            get {
                return ResourceManager.GetString("page_title_new_clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo empleado.
        /// </summary>
        internal static string page_title_new_employee {
            get {
                return ResourceManager.GetString("page_title_new_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string page_title_profile {
            get {
                return ResourceManager.GetString("page_title_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string page_title_settings {
            get {
                return ResourceManager.GetString("page_title_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratar.
        /// </summary>
        internal static string payment_product_button_buy {
            get {
                return ResourceManager.GetString("payment_product_button_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string payment_product_current_cancel {
            get {
                return ResourceManager.GetString("payment_product_current_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /mes.
        /// </summary>
        internal static string payment_product_info_month {
            get {
                return ResourceManager.GetString("payment_product_info_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispone de de {0} por cada cliente.
        /// </summary>
        internal static string payment_product_info_row_money {
            get {
                return ResourceManager.GetString("payment_product_info_row_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso a las aplicaciones móviles para tus clientes..
        /// </summary>
        internal static string payment_product_info_row_phone {
            get {
                return ResourceManager.GetString("payment_product_info_row_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soporte y mejoras continuas. Trabajamos continuamente en mejorar el sistema.
        /// </summary>
        internal static string payment_product_info_row_support {
            get {
                return ResourceManager.GetString("payment_product_info_row_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar contraseña.
        /// </summary>
        internal static string recover_pass {
            get {
                return ResourceManager.GetString("recover_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que quiere eliminar este empleado?.
        /// </summary>
        internal static string remove_employee_message {
            get {
                return ResourceManager.GetString("remove_employee_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar empleado.
        /// </summary>
        internal static string remove_employee_title {
            get {
                return ResourceManager.GetString("remove_employee_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repite la nueva contraseña.
        /// </summary>
        internal static string repeat_new_pass {
            get {
                return ResourceManager.GetString("repeat_new_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol de empleado.
        /// </summary>
        internal static string rol_of_employee {
            get {
                return ResourceManager.GetString("rol_of_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar cambios.
        /// </summary>
        internal static string save_changes {
            get {
                return ResourceManager.GetString("save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar clientes....
        /// </summary>
        internal static string search_clients {
            get {
                return ResourceManager.GetString("search_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar clínicas....
        /// </summary>
        internal static string search_clinics_dots {
            get {
                return ResourceManager.GetString("search_clinics_dots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver detalle.
        /// </summary>
        internal static string see_detail {
            get {
                return ResourceManager.GetString("see_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver perfil.
        /// </summary>
        internal static string see_profile {
            get {
                return ResourceManager.GetString("see_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonidos.
        /// </summary>
        internal static string sounds {
            get {
                return ResourceManager.GetString("sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscripción.
        /// </summary>
        internal static string subscription {
            get {
                return ResourceManager.GetString("subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        internal static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar plan.
        /// </summary>
        internal static string update_plan {
            get {
                return ResourceManager.GetString("update_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir imágenes.
        /// </summary>
        internal static string upload_images {
            get {
                return ResourceManager.GetString("upload_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir sonidos.
        /// </summary>
        internal static string upload_sounds {
            get {
                return ResourceManager.GetString("upload_sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir videos.
        /// </summary>
        internal static string upload_videos {
            get {
                return ResourceManager.GetString("upload_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión:.
        /// </summary>
        internal static string version_prefix {
            get {
                return ResourceManager.GetString("version_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string videos {
            get {
                return ResourceManager.GetString("videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
