trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - src/Api
    - src/Common/FreyaPayments.Core
    - src/Common/Models.Core
    - src/Common/UploaderWasabi
    - pipelines/api-CD.yml

parameters:
- name: AppVersion
  displayName: App Version (ej. 1.2)
  default: 1.1
  type: string

pool:
  vmImage: ubuntu-latest

variables:
  - group: net-versions
  - name: csproj
    value: 'src/Api/FreyaApi/FreyaApi.csproj'
  - name: buildConfiguration
    value: 'Release'
  - name: appVersion
    value: ${{parameters.AppVersion}}
  - name: appVersionBuild
    value: $[counter(variables.appVersion, 1000)]  
    
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(net-7)'
    includePreviewVersions: false

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'FreyaApi.sln'

- task: Assembly-Info-NetCore@3
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: $(csproj)
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    Authors: 'Freya'
    Company: 'Freya'
    Copyright: 'Copyright © $(date:YYYY) Freya Api'
    VersionNumber: '$(appVersion).$(appVersionBuild)'
    PackageVersion: '$(appVersion).$(appVersionBuild)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false
    UpdateBuildNumber: '$(appVersion).$(appVersionBuild)'
    AddBuildTag: '$(appVersion).$(appVersionBuild)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(csproj)
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '-r linux-x64 --self-contained true --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    workingDirectory: 'src/Api/FreyaApi'

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'Freya Api'