namespace Models.Core.Employees;

public enum NewEmployeeState
{
    EMPLOYEE_NOT_REGISTERED,
    EMPLOYEE_REGISTERED_AND_ASIGNED,
    EMPLOYEE_REGISTERED_BUT_NOT_ASIGNED,
    EMPLOYEE_REGISTERED_FOR_OTHER_COMPANY,
    CAN_NOT_REGISTER_COMPANY_EMPLOYEE_TO_INDIVIDUAL_CLINIC
}
